#version 450

#extension GL_GOOGLE_include_directive : enable
#include "ssaoBlur.glsl"

layout(local_size_x_id = 0, local_size_y_id = 1) in;
layout(set = 0, binding = 2, r8) uniform image2D outBlurred;

void main() {
	uvec2 size = imageSize(outBlurred);
	uvec2 pixel = gl_GlobalInvocationID.xy;
	if(pixel.x >= size.x || pixel.y >= size.y) {
		return;
	}

	vec2 pixelSize = 1.f / size;
	vec2 uv = (pixel + 0.5) * pixelSize;
	imageStore(outBlurred, ivec2(pixel), vec4(ssaoBlur(uv)));
}

